// Marquee.js
import React from "react";
import "../App.css"; // Import the stylesheet

const Marquee = () => {
  return (
    <div className="marquee">
      <div className="track">
        <div className="content">
          &nbsp;HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS
          HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK
          GENESIS HACK GENESIS HACK GENESIS HACK GENESIS HACK GENESIS{" "}
        </div>
      </div>
    </div>
  );
};

export default Marquee;
